site_name: template-mkdocs
repo_url: https://github.com/Sydney-Informatics-Hub/template-mkdocs
repo_name: Sydney-Informatics-Hub/template-mkdocs

nav:
  # Landing page
  - Home: index.md 
  - Setup: setup.md
  - Lesson plan: lesson_plan.md
  - Sesson 1:
    - 1.0 Introduction to session 1: session_1/1.0_intro.md
    - 1.1 Introduction to nf-core and Nextflow: session_1/1.1_nfcore.md
    - 1.2 Running nf-core workflows: session_1/1.2_run.md
    - 1.3 Configuring nf-core workflows: session_1/1.3_configure.md
    - 1.4 Introduction to nf-core/rnaseq: session_1/1.4_rnaseq.md
  - Session 2:
    - 2.0 Introduction to session 2: session_2/2.0_intro.md
    - 2.1 nf-core workflow parameters: session_2/2.1_params.md
    - 2.2 Nextflow configuration files: session_2/2.2_config.md
    - 2.3 Further customisations: session_2/2.3_custom.md
  - Tips & tricks: tips_tricks.md

theme:
  name: material
  logo: assets/usyd-logo.png
  features:
    - navigation.footer
    - content.code.copy
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  analytics:
    provider: google
    property: G-TNWWV3HK57
